library(nycflights13)
data(flights)
?flights
str(flights)
View(flights)
library(dplyr)
flights %>% filter(dest == "SFO")
flights %>% filter(dest == "SFO" | dest == "SJC" | dest == "OAK")
Stanford <- flights %>% filter(dest == "SFO" | dest == "SJC" | dest == "OAK")
Stanford %>% filter(month <= 6 | month >= 9)
Stanford %>% filter(month != 7 & month != 8)
Stanford %>% select(year, month, day)
Stanford %>% select(day, month, year, everything())
Stanford %>% arrange(dep_delay)
Stanford %>% arrange(desc(dep_delay))
library(ggplot2)
ggplot(data = Stanford) + geom_histogram(aes(x = air_time))
ggplot(data = Stanford) + geom_histogram(aes(x = air_time)) + facet_grid(origin ~ dest)
ggplot(data = Stanford) + geom_histogram(aes(x = air_time)) + facet_grid(dest~origin, scales = "free_y")
Stanford %>% summarize(mean_airtime = mean(air_time))
Stanford %>% summarize(mean_airtime = mean(air_time, na.rm = TRUE))
Stanford %>% summarize(median_airtime = median(air_time, na.rm = TRUE))
Stanford %>% group_by(carrier) %>% summarize(mean_airtime = mean(air_time, na.rm = TRUE))
Stanford %>% group_by(carrier) %>% summarize(mean_airtime = mean(air_time, na.rm = TRUE)) %>% arrange(desc(mean_airtime))